name: Deploy Resume to Github Pages
on: 
  push:
    branches:
      - main

jobs:

  site-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code code
        uses: actions/checkout@v3
      - name: Create docs folder
        run: mkdir docs
      - name: Copy all files to docs
        run: cp * docs
      - name: Deploy Pages site
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
