name: Deploy Resume to Github Pages
on: 
  pull-request:
    branches:
      - main

jobs:

  site-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code code
        uses: actions/checkout@v3
      - name: Create pages directory
        run: mkdir docs
      - name: Deploy Pages site
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
