
name: Deploy Lambda Function
on: 
  push:
    paths:
      - index.html

jobs:

  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code code
        uses: actions/checkout@v3
      - name: Deploy Pages site
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs
